name = "Factions"
prefix = "factions"
mainprefix = "synixe"

[version]
git_hash = 0

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE3
    "497660133", # CUP Weapons
    "497661914", # CUP Units
    "541888371", # CUP Vehicles
]

[files]
include = []